ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        sslPort = 8443
        sslPort = ${?SSL_PORT}
    }
    application {
        modules = [ com.landonpatmore.yahoofantasybot.backend.ApplicationKt.module ]
    }
    security {
        ssl {
            keyStore = certificates/keystore.p12
            keyAlias = "localhost"
            keyStorePassword = "changeit"
            privateKeyPassword = "changeit"
        }
    }
}
